import type { TraceEvidence, TraceStage } from '../../types/api';
import { BASE_LABELS } from './traceLabels';
export const evidenceRecords = (value: unknown): TraceEvidence[] => Array.isArray(value) ? value.filter((v): v is TraceEvidence => !!v && typeof v === 'object') : [];
const idOf = (e: TraceEvidence) => String(e.chunk_id ?? e.evidence_id ?? e.id ?? 'Evidência');
const fmt = (n: number | null | undefined, digits: number) => typeof n === 'number' ? n.toFixed(digits) : '—';
const scoreColumn: Record<string, string> = { retrieval_denso: 'dense', retrieval_bm25: 'bm25', fusao_rrf: 'rrf', rerank: 'rerank' };
const shortId = (id: string) => id.length > 28 ? `${id.slice(0, 12)}…${id.slice(-10)}` : id;
export function ranksBefore(etapas: TraceStage[], current: number): Map<string, number> { const fusion = etapas.slice(0, current).filter((stage) => stage.stage === 'fusao_rrf').at(-1); return new Map(evidenceRecords(fusion?.detalhes.evidencias).map((e, index) => [idOf(e), Number(e.rank ?? index + 1)])); }
export function EvidenceTable({ stage, previousRanks }: { stage: TraceStage; previousRanks: Map<string, number> }) {
  const items = evidenceRecords(stage.detalhes.evidencias); if (!items.length) return null;
  const omitted = Number(stage.detalhes.evidencias_fora_do_log ?? 0), current = scoreColumn[stage.stage], candidates = Number(stage.detalhes.candidatos ?? 0);
  const active = (column: string) => current === column ? 'trace-score-current' : undefined;
  return <>{stage.stage === 'rerank' && candidates > 0 ? <p className="trace-candidates">Reordenou {candidates} candidatos</p> : null}<div className="trace-table-wrap"><table className="trace-evidence-table"><thead><tr><th>Posição</th><th>Trecho</th><th>Base</th><th className={active('dense')}>Densa</th><th className={active('bm25')}>BM25</th><th className={active('rrf')}>RRF</th><th className={active('rerank')}>Rerank</th><th>Movimento</th></tr></thead><tbody>{items.map((e, index) => { const id = idOf(e), rank = Number(e.rank ?? index + 1), before = previousRanks.get(id), move = before === undefined ? null : before - rank, source = String(e.source_file ?? ''), title = [source, id].filter(Boolean).join('\n'); return <tr key={`${id}-${index}`}><td>{rank}</td><td title={title}><span>{source || shortId(id)}</span>{source && source !== id ? <small className="trace-chunk-id">{shortId(id)}</small> : null}{e.identificador_pncp_exato ? <small>nº PNCP exato</small> : null}</td><td>{BASE_LABELS[String(e.base_id)] ?? String(e.base_id ?? '—')}</td><td className={active('dense')}>{fmt(e.dense_score ?? (stage.stage === 'retrieval_denso' ? e.score : null), 4)}</td><td className={active('bm25')}>{fmt(e.sparse_score ?? (stage.stage === 'retrieval_bm25' ? e.score : null), 2)}</td><td className={active('rrf')}>{fmt(e.rrf_score ?? (stage.stage === 'fusao_rrf' ? e.score : null), 4)}</td><td className={active('rerank')}>{fmt(e.rerank_score ?? (stage.stage === 'rerank' ? e.score : null), 4)}</td><td>{move === null ? '—' : `${before}º → ${rank}º ${move > 0 ? `↑ ${move}` : move < 0 ? `↓ ${Math.abs(move)}` : '—'}`}</td></tr>; })}</tbody></table>{omitted > 0 ? <p>+{omitted} candidatos não registrados no log</p> : null}</div></>;
}
