import type { TraceStage } from '../../types/api';
import { formatMs } from './traceLabels';
const recordOf = (value: unknown): Record<string, unknown> => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
const numberOf = (...values: unknown[]) => values.find((value) => typeof value === 'number') as number | undefined;
function Tokens({ value }: { value: unknown }) { const t = recordOf(value); const input = numberOf(t.prompt, t.input, t.prompt_tokens, t.input_tokens); const output = numberOf(t.completion, t.output, t.completion_tokens, t.output_tokens); const total = numberOf(t.total, t.total_tokens) ?? (input !== undefined || output !== undefined ? (input ?? 0) + (output ?? 0) : undefined); return <>{input !== undefined ? <p>Tokens de entrada: {input}</p> : null}{output !== undefined ? <p>Tokens de saída: {output}</p> : null}{total !== undefined ? <p>Tokens totais: {total}</p> : null}</>; }
export function ModelUsage({ stage }: { stage: TraceStage }) {
  const d = stage.detalhes, llm = recordOf(d.llm), tokens = stage.tokens ?? llm.tokens ?? d.tokens;
  const provider = llm.provider ?? d.provider, model = llm.model ?? llm.model_requested ?? d.model ?? stage.modelo;
  const calls = Array.isArray(d.chamadas_modelo) ? d.chamadas_modelo.filter((call) => call && typeof call === 'object') as Record<string, unknown>[] : [];
  const embedding = recordOf(d.query_embedding), fallback = llm.fallback_used === true || d.fallback_used === true || provider === 'openrouter';
  const finishReason = llm.finish_reason ?? d.finish_reason, latency = numberOf(llm.latencia_ms, d.latencia_ms);
  if (!model && !provider && !Object.keys(recordOf(tokens)).length && !calls.length && !embedding.cache_hits) return null;
  return <section className="trace-model"><h4>Uso do modelo</h4>{model ? <p>Modelo: {String(model)}</p> : null}{provider ? <p>Provedor: {String(provider)}</p> : null}<Tokens value={tokens} />{latency !== undefined ? <p>Latência: {formatMs(latency)}</p> : null}{llm.mode ? <p>Modo: {String(llm.mode)}</p> : null}{llm.content_chars !== undefined ? <p>Caracteres gerados: {String(llm.content_chars)}</p> : null}{llm.reasoning_tokens !== undefined ? <p>Tokens de raciocínio: {String(llm.reasoning_tokens)}</p> : null}{fallback ? <span className="trace-model-alert">fallback OpenRouter</span> : null}{finishReason === 'length' ? <p className="trace-model-alert">O modelo atingiu o limite de tokens antes de terminar.</p> : null}{Number(embedding.cache_hits ?? 0) > 0 ? <p>Embedding reaproveitado do cache</p> : null}{calls.length ? <div className="trace-model-calls"><h4>Chamadas ao modelo</h4>{calls.map((call, index) => <article key={index}><strong>Chamada {index + 1}</strong>{call.provider ? <p>Provedor: {String(call.provider)}</p> : null}{call.model ?? call.model_requested ? <p>Modelo: {String(call.model ?? call.model_requested)}</p> : null}{call.status ? <p>Status: {String(call.status)}</p> : null}{typeof call.latencia_ms === 'number' ? <p>Latência: {formatMs(call.latencia_ms)}</p> : null}<Tokens value={call.tokens} />{call.error_type ? <p>Tipo do erro: {String(call.error_type)}</p> : null}</article>)}</div> : null}</section>;
}
