import type { TraceStage } from '../../types/api';
import { BASE_LABELS, SKIP_REASONS } from './traceLabels';
const REASONS: Record<string, string> = { reescrita: 'reescrita pelo modelo', troca_de_ano: 'ano trocado por regra, sem modelo', saida_invalida: 'o modelo respondeu fora do formato; o contexto anterior foi utilizado', llm_falhou: 'o modelo não respondeu; o contexto anterior foi utilizado', autossuficiente: 'a pergunta já fazia sentido sozinha' };
const recordOf = (value: unknown): Record<string, unknown> => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
const filled = (value: unknown) => value !== null && value !== undefined && value !== false && value !== '' && (!Array.isArray(value) || value.length > 0) && (typeof value !== 'object' || Array.isArray(value) || Object.keys(value as object).length > 0);
const text = (value: unknown): string => Array.isArray(value) ? value.map(String).join(', ') : typeof value === 'object' ? Object.entries(value as Record<string, unknown>).map(([key, val]) => `${key.replaceAll('_', ' ')}: ${String(val)}`).join(', ') : String(value);
const Note = ({ label, value }: { label: string; value: unknown }) => filled(value) ? <p><strong>{label}:</strong> {text(value)}</p> : null;
export function StageNotes({ stage }: { stage: TraceStage }) {
  const input = recordOf(stage.input), output = recordOf(stage.output), d = stage.detalhes, status = String(d.outcome ?? stage.status), reason = d.motivo ?? d.razao ?? output.motivo;
  let content = null;
  if (stage.stage === 'reformulacao') content = <><Note label="Pergunta original" value={input.pergunta ?? input.query ?? (typeof stage.input === 'string' ? stage.input : d.pergunta_original)} /><Note label="Pergunta consultada" value={output.pergunta ?? output.reescrita ?? d.pergunta_reformulada} /><Note label="Motivo" value={reason ? REASONS[String(reason)] ?? reason : null} /><Note label="Turnos usados como contexto" value={d.turnos_no_prompt ?? d.turnos_usados} /></>;
  if (stage.stage === 'query_analysis') { const source = { ...d, ...output }; content = <>{[['ano','Ano'],['periodo','Período'],['metrica','Métrica'],['agrupamentos','Agrupamento'],['filtros','Filtros'],['referencia_temporal','Referência temporal'],['filtros_analiticos','Filtros analíticos']].map(([key,label]) => <Note key={key} label={label} value={source[key]} />)}</>; }
  if (stage.stage === 'roteamento') { const bases = output.bases ?? d.bases; content = <><Note label="Bases escolhidas" value={Array.isArray(bases) ? bases.map((base) => BASE_LABELS[String(base)] ?? base) : bases} /><Note label="Justificativa" value={output.justificativa ?? d.justificativa} /><Note label="Confiança" value={output.confianca ?? output.confidence ?? d.confianca ?? d.confidence} /></>; }
  if (stage.stage === 'geracao') content = <><Note label="Trechos no prompt" value={d.chunks_no_prompt} /><Note label="Fora por limite de contexto" value={d.chunks_fora_do_orcamento ?? d.chunks_excluidos_orcamento} /><Note label="Trechos restritos descartados" value={d.restritos_descartados} /><Note label="Dados pessoais ocultados" value={d.mascaramentos} /></>;
  if (stage.stage === 'validacao') content = <><Note label="Citações confirmadas" value={d.citacoes_aceitas} /><Note label="Citações descartadas" value={d.citacoes_descartadas} />{d.json_valido === false ? <p>A resposta do modelo não veio no formato esperado.</p> : null}{d.recusa_convertida ? <p>Uma recusa indevida foi convertida.</p> : null}<Note label="Dados pessoais ocultados na resposta" value={d.mascaramentos_resposta} /></>;
  return <>{status === 'pulado' && reason ? <p>{SKIP_REASONS[String(reason)] ?? text(reason)}</p> : null}{status === 'degradado' && filled(d.fallback) ? <p><strong>Plano B:</strong> {text(d.fallback)}</p> : null}{['erro','erro_llm','saida_invalida'].includes(status) && filled(d.error_type) ? <p className="trace-error-type">Tipo do erro: {text(d.error_type)}</p> : null}{content}</>;
}
